fix: build failed on archlinux
error: 'SurfaceEntry' defined as a struct here but previously declared
as a class; this is valid, but may result in linker errors under the
Microsoft C++ ABI [-Werror,-Wmismatched-tags].

(cherry picked from commit 17e505b67416d1dbd167ea966043106e77e61e1c)

[treeland-sync] classification: other
[treeland-sync] action: applied
[treeland-sync] drop files:
- none
[treeland-sync] path mapping:
- src/modules/foreign-toplevel/foreigntoplevelmanagerv1.cpp -> compositor/src/modules/foreign-toplevel/foreigntoplevelmanagerv1.cpp
[treeland-sync] adaptation paths:
- none
[treeland-sync] adaptation notes:
- none

Treeland-Remote: treeland
Treeland-Remote-Branch: master
Treeland-Tracking-Ref: refs/remotes/treeland/master
Treeland-Commit: 17e505b67416d1dbd167ea966043106e77e61e1c